## Домен/поддомен по которому будет открываться панель и работать подключение с TLS 
## При создании подключения необходимо указывать в "Хост" при выборе xhttp, httpupgrade, WebSocket (далее ws)
main_domain: example.com

## Можно оставить по умолчанию.
# Порты для доступа к подключениям по протоколам, порты потребуется указывать при создании подключения 
xhttp_port: 10001
ws_port: 10002
httpupgrade_port: 10003

# Пути для доступа к подключениям по протоколам, пути потребуется указывать при создании подключения
xhttp_path: /xhttp
ws_path: /ws
httpupgrade_path: /httpupgrade

# Аналогично пунктам выше, но для подписок (ссылка клиента с данными)
# При изменении в настройках панели необходимо изменить тут
sub_port: 2096
sub_path: /sub

